### ISSUE TITLE
empty txt files generated

### ISSUE THREAD

**Issue by ashokrajagopal68** [WyattAutomation/Train-YOLOv3-with-OpenImagesV4#2]
After setting the csv path and running the code for a single class I was able to generate all the txt files for each image in that directory. But the problem is that the txt files are empty. How to solve this.

**Comment by WyattAutomation** [comment]
Assuming you’re using Linux, it should just work.  

Did you include the full directory path in the CSV path?  Like /home/uname/Desktop and not like ./csvfolder or something like that?

**Comment by WyattAutomation** [comment]
Also, I believe there is an extra “/“ that may or may not be added depending on your OS for the path of the CSV files that the script is looking for.  

Try some print() statements to make sure the script is pointing at the right path.

**Comment by ashokrajagopal68** [comment]
It's done.
I had given the path to the wrong csv
Thank you.. Great work.... Awesome repo.

**Comment by WyattAutomation** [comment]
Thanks!  I have been struggling to find time, but I will update it soon for multiple classes, so stay tuned!

**Comment by 0338Tayyaba** [comment]
> It's done. I had given the path to the wrong csv Thank you.. Great work.... Awesome repo.

i am facing same issue, how you gave the right csv path?
