### ISSUE TITLE
.h5 or .pb convert?

### ISSUE THREAD

**Issue by ghost** [WyattAutomation/Train-YOLOv3-with-OpenImagesV4#3]
i wanna convert .weights to .h5 or .pb. how to do that?

**Comment by WyattAutomation** [comment]
Well, that depends on what you need that for.

Are you using a Python/Tensorflow version of YOLOv3?  Maybe like, someone's model that doesn't have instructions for training, and need the weights you make here converted?

I'm currently working on documentation on how to make the model (the original used here, written in C) trigger mute/unmute of looping audio samples using the VLC C API.  It will be a basic guide on how to trigger events  using YOLOv3's object detection. 

If you are looking for instructions on how to apply YOLO for something like that, I will be posting a new repo for that soon.

If you absolutely *have* to have the weights in that format and you are using a remake of this model in Python etc then let me know.  There is 0 documentation I am aware of on how to do this, but if a lot of people need something like this I may be convinced to deliver.

**Comment by WyattAutomation** [comment]
I'll leave this open until you reply; will close it in a week or so if you don't.
