### ISSUE TITLE
File "main.py", line 36, in <module> bounding_boxes_images

### ISSUE THREAD

**Issue by bertalanimre** [WyattAutomation/Train-YOLOv3-with-OpenImagesV4#4]
Hey Wyatt,

Thanks for this awesome readme and all your work, this helps me a lot. :) I just ran into an issue, maybe you already encountered it. It is not a show-stopper, I was able to continue, but I think it might worth a peek.

Scenario:
I was trying to train YoloV3 to recognize deers. So following your guidance I've started downloading deer type classes and then this happened:

```
[DOWNLOAD] | File test-annotations-bbox.csv downloaded into OID/csv_folder/test-annotations-bbox.csv.

--------------------------------------------------------------------------------------------------------Deer--------------------------------------------------------------------------------------------------------
    [INFO] | Downloading all images.
    [INFO] | [INFO] Found 280 online images for test.
    [INFO] | Download of 280 images in test.
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 280/280 [00:38<00:00,  6.87it/s]
    [INFO] | Done!
    [INFO] | Creating labels for Deer of test.
    [INFO] | Labels creation completed.
Traceback (most recent call last):
  File "main.py", line 36, in <module>
    bounding_boxes_images(args, DEFAULT_OID_DIR)
  File "/home/bi/darknet/OIDv4_ToolKit/modules/bounding_boxes.py", line 89, in bounding_boxes_images
    download(args, df_val, folder[i], dataset_dir, class_name, class_code, threads = int(args.n_threads))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

All the requirements are installed, and also installed openCV via pip. 

Have you seen this before?

**Comment by WyattAutomation** [comment]
Hhmmmm.  I have not.  

Did it download the actual images though?  It looks like it failed to make the "labels", which you aren't even using the labels that the downloader makes anyway.  As long as you have the CSV from Open Images, and the images downloaded, you should be fine to proceed and ignore this.

I may in fact release my own downloader script in the future to avoid this.

Anyway, let me know if it appears that you got the CSV and the images downloaded; if so you can ignore this as you aren't going to use *those* labels (the ones generated from that script, which I didn't make) anyway.  The error looks like it's not able to generate some string value (type "NoneType" errors usually mean some variable in the script wasn't populated with a value), but this is an appendix of that script that is unused in the tutorial anyway.  

Let me know if there are other issues and I'll follow up.  I will consider this as a request for a "feature update", to remove or append the OIDv4 downloader tool to not auto-generate the unused labels.  I may even append it with my own scripts so that it generates the legit labels all in one script.  

Best answer I have is that any time spent on this is best used to remove that un-needed appendix from the script.  Going ahead and closing, let me know if you have other issues!

**Comment by bertalanimre** [comment]
Yee, you have it right. I've written it is not a show-stopper error, the PC is learning ATM ( without a graphics card soooooo F me :D ) It did download the images and the CSV files. The labels were missing, but you wrote in your readme that they are not necessary, that is why I continued with the tutorial.

**Comment by WyattAutomation** [comment]
Yep.  I will update in the future to remove that part.  Lemme know if it gums up anything else and I'll follow up as needed.

**Comment by bertalanimre** [comment]
OFF Topic, but:
I'm pretty sure, I've downloaded about 2100 picture regarding to "Deer". But now, the training is at 3400 image and still counting. What the hell? :D What did I do wrong? I have 1800 jpg file in the folder I've set for training, but then how am I at 3400+ images now?

**Comment by WyattAutomation** [comment]
The training may be looping back through images.

2100 is *barely* enough for this.  I'm honestly not super certain how well it will do.  For example, "Human head" which is what you see in the demo, had 49,000+ images.  

Do you see any weights that it's generated yet?

**Comment by bertalanimre** [comment]
Saw one. Yes. Do you recon, I can test with it already?

**Comment by WyattAutomation** [comment]
Hmmmmm.  No I would wait.  What is the number next to your weights file?  Or does it just say .backup at the end?

I usually wait until you see the one that ends in ".backup". That's the one you will want to use

**Comment by bertalanimre** [comment]
naa, I have a deer_100.weight and a 200. Also a backup file

**Comment by WyattAutomation** [comment]
Wait until you see the 900 file, then wait a little longer (hour or so depending on how long each 100 interval takes).

Honestly I'd just let it run all day/night (12 hour cycle on the card I used) and come back to it.  Always use the . backup, if it sucks then try the 900.

**Comment by bertalanimre** [comment]
What Graphics card did you use if I may ask? :D I'm using Intel® HD Graphics 630 because this is all I have :P

**Comment by WyattAutomation** [comment]
Oof.  How on earth you even got this far is astounding.  You almost certainly won't be able to run inference on that, and I'm not even sure how you got it training?  This tutorial is for running it on CUDA 10 (nvidia), lol how on Earth did you even get it training on that??  Sounds like it's actually making progress too? 

I'm using an NVidia gtx 1060, 6GB model (cheapo pny model).  Pretty good NVidia bang-for-your-buck; about $200USD.  With a Ryzen 3 cpu/board combo it makes a great little 'po-boy' ML rig for about $480-600.

Yeah you will need to read PJ Reddie's instructions here, for compiling YOLOv3 with CUDA and OpenCV once you get your hands on an NVidia card:

https://pjreddie.com/darknet/install/#cuda

**Comment by bertalanimre** [comment]
Let's just say I'm a bit more than depressed right now. :D I have no Nvidia card for the office (but gonna buy one soon I think), but however I have a laptop with an Intel 4870HQ CPU and Geforce GTX 960M.

I had hell of a nightmare to make the NVidia gpu the primary (and I'm still not sure if I've made it) but the training speed is almost the same as it was in the office. I assume, darknet is not using the GPU, but the iGPU. I say some kind of `-gpus 0,1` on other threads, but that doesn't seem to speed it up. Do you have the knowledge maybe how to tell darknet which gpu should it use?
