### ISSUE TITLE
Taking long while to train one iteration

### ISSUE THREAD

**Issue by bellaav** [WyattAutomation/Train-YOLOv3-with-OpenImagesV4#8]

**Comment by bellaav** [comment]
I was being dumb, whoops

**Comment by WyattAutomation** [comment]
No biggy m8; I've got issues piling up for this repo that I've neglected to fix due to other projects that I'm absolutely buried in right now, so you closing them out is doing one better than I am at the moment.

I need to return to this and improve it; it does appear to be useful to some folks.
